# Generated by Django 3.2.9 on 2021-12-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='available_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wanted_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
