# Generated by Django 4.2.4 on 2023-08-14 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.IntegerField(choices=[(1, 'daraz'), (2, 'sastodeal'), (3, 'dealayo')], default=1)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=150)),
                ('wished_price', models.IntegerField(default=0)),
                ('available_price', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
