# Generated by Django 3.2.9 on 2021-11-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='exp_date',
            field=models.DateTimeField(null=True),
        ),
    ]
