# Generated by Django 3.2.9 on 2021-11-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userotp_exp_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotp',
            name='exp_date',
        ),
    ]
